### ISSUE TITLE
Error running spark-submit example

### ISSUE THREAD

**Issue by namabile** [mesosphere/dcos-spark#30] opened 2016-04-23 14:26 UTC
I'm following the [Spark tutorial](https://dcos.io/docs/1.7/usage/tutorials/spark/) in the documentation. I'm getting an error saying DCOS is unable to connect to the Mesos server.

Here is some info about my environment:
```
julieweldon@juliewemacbook2:~/dcos$ python --version
Python 2.7.10
julieweldon@juliewemacbook2:~/dcos$ which python
/Users/julieweldon/dcos/bin/python
```

Here is the stack trace:
```
julieweldon@juliewemacbook2:~/dcos$ dcos spark run --submit-args='-Dspark.mesos.coarse=true --driver-cores 1 --driver-memory 1024M --class org.apache.spark.examples.SparkPi https://downloads.mesosphere.com/spark/assets/spark-examples_2.10-1.4.0-SNAPSHOT.jar 30'
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57380)
Traceback (most recent call last):
  File "/Users/julieweldon/anaconda/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/julieweldon/anaconda/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/Users/julieweldon/anaconda/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/julieweldon/anaconda/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/Users/julieweldon/anaconda/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Users/julieweldon/anaconda/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Users/julieweldon/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 404, in do_POST
    self._request('POST')
  File "/Users/julieweldon/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 442, in _request
    resp = urllib.request.urlopen(req)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 431, in open
----------------------------------------
    response = self._open(req, data)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57382)
Traceback (most recent call last):
  File "/Users/julieweldon/anaconda/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/julieweldon/anaconda/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/Users/julieweldon/anaconda/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
----------------------------------------
  File "/Users/julieweldon/anaconda/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/Users/julieweldon/anaconda/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Users/julieweldon/anaconda/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Users/julieweldon/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 404, in do_POST
    self._request('POST')
  File "/Users/julieweldon/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 442, in _request
    resp = urllib.request.urlopen(req)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/Users/julieweldon/anaconda/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Spark submit failed:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/04/23 10:20:21 INFO RestSubmissionClient: Submitting a request to launch an application in mesos://localhost:57379.
16/04/23 10:20:22 WARN RestSubmissionClient: Unable to connect to server mesos://localhost:57379.
Exception in thread "main" org.apache.spark.deploy.rest.SubmitRestConnectionException: Unable to connect to server
	at org.apache.spark.deploy.rest.RestSubmissionClient$$anonfun$createSubmission$3.apply(RestSubmissionClient.scala:107)
	at org.apache.spark.deploy.rest.RestSubmissionClient$$anonfun$createSubmission$3.apply(RestSubmissionClient.scala:89)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at org.apache.spark.deploy.rest.RestSubmissionClient.createSubmission(RestSubmissionClient.scala:89)
	at org.apache.spark.deploy.rest.RestSubmissionClient$.run(RestSubmissionClient.scala:444)
	at org.apache.spark.deploy.rest.RestSubmissionClient$.main(RestSubmissionClient.scala:457)
	at org.apache.spark.deploy.rest.RestSubmissionClient.main(RestSubmissionClient.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:786)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:183)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:208)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:123)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.deploy.rest.SubmitRestConnectionException: Unable to connect to server
	at org.apache.spark.deploy.rest.RestSubmissionClient.readResponse(RestSubmissionClient.scala:293)
	at org.apache.spark.deploy.rest.RestSubmissionClient.org$apache$spark$deploy$rest$RestSubmissionClient$$postJson(RestSubmissionClient.scala:253)
	at org.apache.spark.deploy.rest.RestSubmissionClient$$anonfun$createSubmission$3.apply(RestSubmissionClient.scala:93)
	... 18 more
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.apache.spark.deploy.rest.RestSubmissionClient$$anonfun$1.apply(RestSubmissionClient.scala:265)
	at org.apache.spark.deploy.rest.RestSubmissionClient$$anonfun$1.apply(RestSubmissionClient.scala:263)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by mgummelt** [comment] 2016-04-26 17:16
Hi, sorry for the delay.  Your `core.dcos_url` is probably set to an HTTPS URL.  DC/OS by default uses a self-signed cert.  There's a `core.ssl_verify` config var to indicate whether to check the cert.  It default to false, but it looks like Spark isn't honoring it.  I'll fix that.

You could either switch to HTTP, or monkey patch the Spark CLI to not check the cert.

**Comment by namabile** [comment] 2016-04-26 20:45
Great. Thanks for the reply. 

I saw the `core.ssl_verify` config value is set to `false`. That was leading me to believe it wasn't an HTTPS issue. I'll try using an HTTP URL.

Is it an issue that the Mesos master URL is set to `mesos://localhost:57379`?

**Comment by mgummelt** [comment] 2016-04-26 21:08
No.  The CLI sets up a temporary forward proxy that `spark-submit` talks to.  This is so we can intercept HTTP requests and add auth tokens.  We should probably print a log message to this effect.

**Comment by g7adrian** [comment] 2016-07-03 20:31
It seems that other subcommands are broken as well. I get the same error with "dcos kafka" and "dcos hdfs". I think they don't honor core.ssl_very = false either. Can someone fix all subcommands? Thanks!

**Comment by mgummelt** [comment] 2016-07-05 16:41
@g7adrian The latest Spark CLI honors ssl.  Can you verify that this solves your problem?

And if you're having a problem with `dcos hdfs` or `dcos kafka`, can you paste that error output here?  I'll ping one of those devs.

**Comment by neerajgoel82** [comment] 2016-07-07 07:01
I was also trying Spark on DC/OS ( I am referring to https://docs.mesosphere.com/1.7/usage/service-guides/spark/install/ ) but I am not able to run the job. 

**Job command:**
 dcos spark run --submit-args="--class org.apache.spark.examples.SparkPi https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark-examples_2.10-1.5.0.jar"

**Error that I am getting:**
Spark distribution spark-1.6.1-2 not found locally.
It looks like this is your first time running Spark!
Downloading https://downloads.mesosphere.com/spark/assets/spark-1.6.1-2.tgz...
ERROR:dcos.http:HTTP SSL Error
Traceback (most recent call last):
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos/http.py", line 96, in _request
    **kwargs)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Traceback (most recent call last):
  File "/home/neeraj/.dcos/subcommands/spark/env/bin/dcos-spark", line 11, in <module>
    sys.exit(main())
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/cli.py", line 102, in main
    return run_spark_job(args)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/cli.py", line 44, in run_spark_job
    args['--verbose'])
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 167, in submit_job
    response = run(dispatcher, args, verbose, props)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 281, in run
    command = _get_command(dispatcher, args)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 349, in _get_command
    submit_file = spark_file(os.path.join('bin', spark_executable))
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 129, in spark_file
    return os.path.join(spark_dist(), path)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 102, in spark_dist
    resp = http.request('GET', spark_uri, stream=True)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos/http.py", line 222, in request
    verify=verify, **kwargs)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos/util.py", line 524, in timer
    return fn(*args, **kwargs)
  File "/home/neeraj/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos/http.py", line 104, in _request
    raise DCOSException(msg)
dcos.errors.DCOSException: An SSL error occurred. To configure your SSL settings, please run: `dcos config set core.ssl_verify <value>`
<value>: Whether to verify SSL certs for HTTPS or path to certs

**DCOS config:**
core.ssl_verify=false
core.dcos_url is also http.

Am I missing something here?

**Comment by mgummelt** [comment] 2016-07-07 18:01
Closing as duplicate of https://github.com/mesosphere/dcos-spark/issues/34

**Closed by mgummelt** 2016-07-07 18:01 UTC
